name: "wait"
version: "0.0.3"
usage: "Wait for helm release upgrades"
description: "Wait for helm release upgrades"
command: "$HELM_PLUGIN_DIR/bin/wait"
hooks:
  install: "cd $HELM_PLUGIN_DIR; scripts/install_plugin.sh"
  update: "cd $HELM_PLUGIN_DIR; scripts/install_plugin.sh"
